steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE}'
      - '-f'
      - 'api/Dockerfile'
      - '.'

# Push the container image to Artifact Registry
images:
  - '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE}'

# Substitution variables (can be overridden via --substitutions flag)
substitutions:
  _LOCATION: 'europe-west9'
  _REPOSITORY: 'pengouins-repo'
  _IMAGE: 'penguin'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
